FROM nvidia/cuda:8.0-cudnn5-devel-centos7
MAINTAINER H2O.AI <ops@h2o.ai>

ENV CUDA_HOME=/usr/local/cuda
ENV PATH=/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH_MORE=/home/$USER/lib/:$CUDA_HOME/lib64/:$CUDA_HOME/lib/:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LD_LIBRARY_PATH_MORE
ENV CUDADIR=/usr/local/cuda/include/
ENV OMP_NUM_THREADS=32
ENV MKL_NUM_THREADS=32
ENV HOME=/root
ENV VECLIB_MAXIMUM_THREADS=32
ENV PATH=$PYENV_ROOT/bin:$PATH

RUN \
  yum install -y curl && \
  yum install -y https://centos7.iuscommunity.org/ius-release.rpm && \
  yum install -y python36u-devel python36u-pip

RUN \
  yum install -y git

RUN \
  yum install -y make

RUN \
  yum install -y \
    openssl-devel \
    zlib-devel \
    bzip2-devel \
    readline-devel \
    libsqlite3x-devel \
    wget \
    curl \
    ncurses-devel \
    xz-devel \
    tk-devel

WORKDIR $HOME
RUN wget https://cmake.org/files/v3.10/cmake-3.10.1.tar.gz
RUN tar xvf cmake-3.10.1.tar.gz

WORKDIR $HOME/cmake-3.10.1
RUN ./configure
RUN make -j6 install

ENV PATH=/usr/local/bin:$PATH

WORKDIR $HOME
RUN rm -rf cmake-3*
RUN yum install -y which
RUN yum erase -y git
RUN yum install -y git2u
RUN yum install -y ccache

RUN yum install -y sudo man

RUN \
    pip3.6 install --upgrade pip && \
    pip3.6 install --upgrade setuptools

RUN yum install -y openblas-devel

RUN yum install -y centos-release-scl-rh && \
    yum install -y devtoolset-3

WORKDIR $HOME
ENV LLVM4=/usr/local
ENV PATH=/usr/local/bin:$PATH

RUN  wget http://releases.llvm.org/4.0.1/llvm-4.0.1.src.tar.xz && \
  tar xvf llvm-4.0.1.src.tar.xz && rm llvm-4.0.1.src.tar.xz && \
  mkdir $HOME/llvm-4.0.1.src/build && \
  cd $HOME/llvm-4.0.1.src/build && \
  cmake .. && make -j4 && make install && \
  cd && cp llvm-4.0.1.src/build/bin/llvm-lit /usr/local/bin/ && rm -rf llvm-4.0.1.src


RUN wget http://releases.llvm.org/4.0.1/cfe-4.0.1.src.tar.xz && \
  tar xvf cfe-4.0.1.src.tar.xz && \
  rm cfe-4.0.1.src.tar.xz && \
  mkdir cfe-4.0.1.src/build && \
  cd $HOME/cfe-4.0.1.src/build && \
  cmake .. && make -j4 && make install && \
  cd && rm -rf $HOME/cfe-4.0.1.src


RUN wget http://releases.llvm.org/4.0.1/openmp-4.0.1.src.tar.xz && \
  tar xvf openmp-4.0.1.src.tar.xz && \
  rm openmp-4.0.1.src.tar.xz && \
  mkdir openmp-4.0.1.src/build && \
  cd openmp-4.0.1.src/build && \
  yum install -y perl-Data-Dumper && \
  cmake .. && make  && make install && \
  cd && rm -rf openmp-4.0.1.src

RUN \
  wget http://releases.llvm.org/4.0.1/libcxx-4.0.1.src.tar.xz && \
  wget http://releases.llvm.org/4.0.1/libcxxabi-4.0.1.src.tar.xz && \
  tar xvf libcxx-4.0.1.src.tar.xz && tar xvf libcxxabi-4.0.1.src.tar.xz && \
  mkdir libcxxabi-4.0.1.src/build && cd libcxxabi-4.0.1.src/build && \
  CC=clang CXX=clang++ cmake .. -DLIBCXXABI_LIBCXX_INCLUDES=/root/libcxx-4.0.1.src/include && \
  make install && cd && cd libcxx-4.0.1.src && mkdir build && cd build && \
  CC=clang CXX=clang++ cmake .. -DLIBCXX_CXX_ABI=libcxxabi -DLIBCXX_CXX_ABI_INCLUDE_PATHS=/root/libcxxabi-4.0.1.src/include \
  -DLIBCXX_CXX_ABI_LIBRARY_PATH=/usr/local/lib && make && make install && cd && \
  rm -rf libcxx*

RUN pip3.6 install llvmlite==0.20.0 wheel

RUN yum install -y swig
