FROM test/py
 
MAINTAINER H2o.ai <ops@h2o.ai>

ENV CUDA_HOME=/usr/local/cuda
ENV PATH=/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH_MORE=/usr/lib64:/home/$USER/lib/:$CUDA_HOME/lib64/:$CUDA_HOME/lib/:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV LD_LIBRARY_PATH=/usr/lib/gcc/ppc64le-redhat-linux/4.8.2:$LD_LIBRARY_PATH:$LD_LIBRARY_PATH_MORE
ENV CUDADIR=/usr/local/cuda/include/
ENV OMP_NUM_THREADS=32
ENV MKL_NUM_THREADS=32
ENV HOME=/root
ENV VECLIB_MAXIMUM_THREADS=32
ENV PYENV_ROOT=$HOME/.pyenv
ENV PATH=$PYENV_ROOT/bin:$PATH
RUN \
   pip3.6 install setuptools --no-cache-dir && \
   ln /usr/local/bin/easy_install-3.6 /usr/local/bin/easy_install && \
   ln /usr/local/bin/pip3.6 /usr/local/bin/pip && \ 
   pip install wheel 

ENV GIT_COMMITER_NAME=datatable
ENV GIT_COMMITER_EMAIL=datatable@h2o.ai

RUN yum install -y which

RUN yum install -y sudo man gfortran-devel

RUN \
    pip3.6 install --upgrade pip
WORKDIR $HOME

RUN yum install -y swig && \
  ln /usr/lib64/libgfortran.so.3 /usr/lib64/libgfortran.so && \
  wget http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz && \
  tar xvf v0.2.20.tar.gz && \
  rm v0.2.20.tar.gz && \
  cd OpenBLAS-0.2.20 && make CBLAS_ONLY=1 && make PREFIX=/usr/local install

ENV OPENBLAS_PREFIX=open
